title: Stickerify
description: Telegram bot to convert images in stickers.
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
logo: src/main/resources/stickerify.svg
show_downloads: false
github:
  owner_name: Roberto Cella
