title: Stickerify - Telegram bot
description: Telegram bot to convert images in the format required to be used as Telegram stickers (512x512 PNGs)
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
logo: src/main/resources/stickerify.svg
show_downloads: true