[versions]
logback = "1.4.5"

[libraries]
imageio-webp = "com.twelvemonkeys.imageio:imageio-webp:3.9.4"
imgscalr = "org.imgscalr:imgscalr-lib:4.2"
junit = "org.junit.jupiter:junit-jupiter:5.9.1"
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
slf4j-api = "org.slf4j:slf4j-api:2.0.6"
telegrambots = "org.telegram:telegrambots:6.4.0"
tika = "org.apache.tika:tika-core:2.6.0"

[bundles]
logback = ["logback-core", "logback-classic", "slf4j-api"]

[plugins]
shadow = "com.github.johnrengelman.shadow:7.1.2"
