[versions]
logback = "1.4.6"

[libraries]
hamcrest = "org.hamcrest:hamcrest-core:2.2"
imageio-webp = "com.twelvemonkeys.imageio:imageio-webp:3.9.4"
imgscalr = "org.imgscalr:imgscalr-lib:4.2"
jave = "ws.schild:jave-all-deps:3.3.1"
junit = "org.junit.jupiter:junit-jupiter:5.9.2"
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
slf4j-api = "org.slf4j:slf4j-api:2.0.7"
telegrambots = "org.telegram:telegrambots:6.5.0"
tika = "org.apache.tika:tika-core:2.7.0"

[bundles]
logback = ["logback-core", "logback-classic", "slf4j-api"]

[plugins]
shadow = "com.github.johnrengelman.shadow:8.1.0"
