name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build --build-arg STICKERIFY_TOKEN=${{ secrets.STICKERIFY_TOKEN }} -t rob93c/stickerify:latest .

      - uses: actions/checkout@v3
      - name: Perform Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - uses: actions/checkout@v3
      - name: Upload the latest Docker image
        run: docker push rob93c/stickerify:latest
