name: Unit tests CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: temurin

      - name: Setup project
        uses: gradle/gradle-build-action@v2

      - name: Execute tests
        run: ./gradlew test
