name: Unit tests CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  gradle:
    name: Execute unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code changes
        uses: actions/checkout@v3

      - name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: temurin

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Setup project
        uses: gradle/gradle-build-action@v2

      - name: Execute tests
        run: ./gradlew test --scan
